name: YouTube Link to YouTube Live

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:

      - name: Install FFmpeg, Deno and yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl

          curl -fsSL https://deno.land/install.sh | sh
          echo "$HOME/.deno/bin" >> "$GITHUB_PATH"

          python3 -m pip install -U yt-dlp

      - name: Create cookies.txt
        run: |
          cat > cookies.txt <<'EOF'
          # Netscape HTTP Cookie File
          # https://curl.haxx.se/rfc/cookie_spec.html

          COOKIES_HERE
          EOF

      - name: Check YouTube Source
        run: |
          echo "Testing YouTube source..."

          yt-dlp \
            --cookies cookies.txt \
            --js-runtimes deno \
            --no-playlist \
            --get-title \
            "https://www.youtube.com/watch?v=gYSm9gakuxc"

      - name: Get Direct Stream URL
        run: |
          yt-dlp \
            --cookies cookies.txt \
            --js-runtimes deno \
            --no-playlist \
            -f "best" \
            -g \
            "https://www.youtube.com/watch?v=gYSm9gakuxc" \
            > source_url.txt

          echo "Source URL obtained."

      - name: Start YouTube Live
        env:
          STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: |
          SOURCE_URL=$(cat source_url.txt)

          ffmpeg \
            -re \
            -i "$SOURCE_URL" \
            -c:v libx264 \
            -preset veryfast \
            -b:v 4500k \
            -maxrate 4500k \
            -bufsize 9000k \
            -pix_fmt yuv420p \
            -g 60 \
            -keyint_min 60 \
            -sc_threshold 0 \
            -c:a aac \
            -b:a 128k \
            -ar 44100 \
            -f flv \
            "rtmps://a.rtmp.youtube.com/live2/$STREAM_KEY"
