name: YouTube Link to YouTube Live

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Install FFmpeg, Deno and yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl
          
          curl -fsSL https://deno.land/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
          
          python3 -m pip install -U yt-dlp

      - name: Test YouTube
        run: |
          yt-dlp --version
          yt-dlp \
            --no-playlist \
            -f "best[ext=mp4]/best" \
            -g \
            "https://www.youtube.com/watch?v=gYSm9gakuxc"

      - name: Start YouTube Live
        run: |
          SOURCE_URL="https://www.youtube.com/watch?v=gYSm9gakuxc"
          STREAM_KEY="YOUR_NEW_STREAM_KEY"

          yt-dlp \
            --no-playlist \
            -f "best[ext=mp4]/best" \
            -o - \
            "$SOURCE_URL" | \
          ffmpeg \
            -re \
            -i pipe:0 \
            -c:v libx264 \
            -preset veryfast \
            -b:v 4500k \
            -maxrate 4500k \
            -bufsize 9000k \
            -pix_fmt yuv420p \
            -g 60 \
            -c:a aac \
            -b:a 128k \
            -ar 44100 \
            -f flv \
            "rtmps://a.rtmp.youtube.com/live2/$STREAM_KEY"
