name: YouTube Live - Video

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 130

    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install gdown
        run: pip install gdown

      - name: Download Video
        run: |
          mkdir -p video
          gdown "https://drive.google.com/uc?id=17p0pvTaQRZ-RVo_t6_1BS55Sl0C8RG87" -O video/input.mp4

      - name: Start YouTube Live
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: |
          ffmpeg \
            -re \
            -stream_loop -1 \
            -i video/input.mp4 \
            -c:v copy \
            -c:a aac \
            -b:a 128k \
            -f flv \
            "rtmp://a.rtmp.youtube.com/live2/${STREAM_KEY}"
