name: Test One Video YouTube Live

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:

      - name: Install FFmpeg and gdown
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip3 install -U gdown

      - name: Download test video
        run: |
          mkdir -p videos

          gdown \
            "https://drive.google.com/uc?id=1Hz3M9eNa0GfuSON06DZwbny6_oEuKuQg" \
            -O "videos/test.mp4"

          ls -lh videos/test.mp4

      - name: Check video
        run: |
          ffprobe -hide_banner videos/test.mp4

      - name: Stream video in loop
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: |
          ffmpeg \
            -re \
            -stream_loop -1 \
            -i "videos/test.mp4" \
            -c:v libx264 \
            -preset veryfast \
            -b:v 6000k \
            -maxrate 6000k \
            -bufsize 12000k \
            -r 30 \
            -g 60 \
            -keyint_min 60 \
            -sc_threshold 0 \
            -pix_fmt yuv420p \
            -c:a aac \
            -b:a 128k \
            -ar 44100 \
            -ac 2 \
            -f flv \
            "rtmp://a.rtmp.youtube.com/live2/${STREAM_KEY}"
